version: "3.9"

services:
  database:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=zitrus
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT=root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3307:3306"
networks:
  askin-bridge:
    driver: bridge